# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kullanici_bilgi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_4(object):
    def setupUi(self, Form_4):
        Form_4.setObjectName("Form_4")
        Form_4.resize(441, 431)
        self.widget_2 = QtWidgets.QWidget(Form_4)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 441, 437))
        self.widget_2.setStyleSheet("background-color: #292f45;\n"
"    color: #000000;\n"
"    border-color: #000000;")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(70, 50, 311, 71))
        self.label.setMinimumSize(QtCore.QSize(231, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 151, 421, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(150, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.ad = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.ad.setFont(font)
        self.ad.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.ad.setText("")
        self.ad.setObjectName("ad")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ad)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(127, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.soyad = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.soyad.setFont(font)
        self.soyad.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.soyad.setText("")
        self.soyad.setObjectName("soyad")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.soyad)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(82, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.kullanici_adi_aktif = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.kullanici_adi_aktif.setFont(font)
        self.kullanici_adi_aktif.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.kullanici_adi_aktif.setText("")
        self.kullanici_adi_aktif.setObjectName("kullanici_adi_aktif")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kullanici_adi_aktif)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(32, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.okunan_kitap_sayisi = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.okunan_kitap_sayisi.setFont(font)
        self.okunan_kitap_sayisi.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.okunan_kitap_sayisi.setText("")
        self.okunan_kitap_sayisi.setObjectName("okunan_kitap_sayisi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.okunan_kitap_sayisi)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.okunmayan_kitap_sayisi = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.okunmayan_kitap_sayisi.setFont(font)
        self.okunmayan_kitap_sayisi.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.okunmayan_kitap_sayisi.setText("")
        self.okunmayan_kitap_sayisi.setObjectName("okunmayan_kitap_sayisi")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.okunmayan_kitap_sayisi)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_7)
        self.okunan_sayfa_sayisi = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.okunan_sayfa_sayisi.setFont(font)
        self.okunan_sayfa_sayisi.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.okunan_sayfa_sayisi.setText("")
        self.okunan_sayfa_sayisi.setObjectName("okunan_sayfa_sayisi")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.okunan_sayfa_sayisi)

        self.retranslateUi(Form_4)
        QtCore.QMetaObject.connectSlotsByName(Form_4)

    def retranslateUi(self, Form_4):
        _translate = QtCore.QCoreApplication.translate
        Form_4.setWindowTitle(_translate("Form_4", "Form"))
        self.label.setText(_translate("Form_4", "Kullanıcı Bilgi"))
        self.label_2.setText(_translate("Form_4", "Ad :"))
        self.label_3.setText(_translate("Form_4", "Soyad :"))
        self.label_7.setText(_translate("Form_4", "Kullanıcı adı : "))
        self.label_13.setText(_translate("Form_4", "Okunan kitap sayısı :"))
        self.label_14.setText(_translate("Form_4", "Okunmayan kitap sayısı :"))
        self.label_12.setText(_translate("Form_4", "Okunan sayfa sayısı :"))