# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(424, 589)
        Form.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-210, -40, 696, 755))
        self.widget.setStyleSheet("background-color: #292f45;\n"
"    color: #000000;\n"
"    border-color: #000000;")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 510, 331, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.hesap_ac = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.hesap_ac.setFont(font)
        self.hesap_ac.setStyleSheet("QPushButton#hesap_ac {\n"
"    background-color:rgba(0,0,0,0);\n"
"    border:none;\n"
"    color:rgba(100, 181, 246);\n"
"    padding-bottom:7px;\n"
"}\n"
"QPushButton#hesap_ac:pressed {\n"
"   color:        #B0BEC5;\n"
"\n"
"}\n"
"")
        self.hesap_ac.setObjectName("hesap_ac")
        self.horizontalLayout.addWidget(self.hesap_ac)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(200, 40, 441, 591))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("background-color: #292f45;\n"
"    color: #000000;\n"
"    border-color: #000000;")
        self.widget_2.setObjectName("widget_2")
        self.giris_yap = QtWidgets.QPushButton(self.widget_2)
        self.giris_yap.setGeometry(QtCore.QRect(255, 380, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.giris_yap.setFont(font)
        self.giris_yap.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #f0742f;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 17px;\n"
"    border-color: #f0742f;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #ff6b35;\n"
"    color: #fff;\n"
"\n"
"}")
        self.giris_yap.setAutoRepeatDelay(300)
        self.giris_yap.setObjectName("giris_yap")
        self.sifre_unuttum = QtWidgets.QPushButton(self.widget_2)
        self.sifre_unuttum.setGeometry(QtCore.QRect(240, 330, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.sifre_unuttum.setFont(font)
        self.sifre_unuttum.setStyleSheet("QPushButton#sifre_unuttum {\n"
"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"\n"
"color:rgba(100, 181, 246);\n"
"padding-bottom:7px;\n"
"}\n"
"QPushButton#sifre_unuttum:pressed {\n"
"   color:        #B0BEC5;\n"
"\n"
"}\n"
"\n"
"")
        self.sifre_unuttum.setObjectName("sifre_unuttum")
        self.sifre = QtWidgets.QLineEdit(self.widget_2)
        self.sifre.setGeometry(QtCore.QRect(90, 250, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sifre.setFont(font)
        self.sifre.setStyleSheet("QLineEdit{\n"
"    background-color: #292f45;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifre.setCursorPosition(0)
        self.sifre.setDragEnabled(False)
        self.sifre.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.sifre.setClearButtonEnabled(True)
        self.sifre.setObjectName("sifre")
        self.kullanici_adi = QtWidgets.QLineEdit(self.widget_2)
        self.kullanici_adi.setGeometry(QtCore.QRect(90, 160, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kullanici_adi.setFont(font)
        self.kullanici_adi.setStyleSheet("QLineEdit{\n"
"    background-color: #292f45;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.kullanici_adi.setClearButtonEnabled(True)
        self.kullanici_adi.setObjectName("kullanici_adi")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(150, 30, 151, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Ekran Alıntısı.PNG"))
        self.label.setObjectName("label")
        self.widget_2.raise_()
        self.horizontalLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.kullanici_adi, self.sifre)
        Form.setTabOrder(self.sifre, self.sifre_unuttum)
        Form.setTabOrder(self.sifre_unuttum, self.giris_yap)
        Form.setTabOrder(self.giris_yap, self.hesap_ac)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Henüz hesabın yok mu?"))
        self.hesap_ac.setText(_translate("Form", "Hesap Aç"))
        self.giris_yap.setText(_translate("Form", "GİRİŞ"))
        self.sifre_unuttum.setText(_translate("Form", "Parolamı Unuttum"))
        self.sifre.setPlaceholderText(_translate("Form", "Parola"))
        self.kullanici_adi.setPlaceholderText(_translate("Form", "Kullanıcı Adı"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())